version: "3"
services:
  webui:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    network_mode: host
    command: /bin/bash
    tty: true
    stdin_open: true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]